services:
  
  cubby:
    image: scribbly/cubby:latest
    container_name: Scribbly-Cubby
    ports:
      - "5000:5000"
  
  cubby-portal:
    image: scribbly/cubby-portal:latest
    container_name: Scribbly-Portal
    ports:
      - "5173:3000"
    environment:
      - CUBBY_HOST_URL=http://Scribbly-Cubby:5000