services:
  scribbly.cubby.hosted:
    image: scribbly.cubby.hosted
    build:
      context: .
      dockerfile: Scribbly.Cubby.Hosted/Dockerfile

  scribbly.cubby.host:
    image: scribbly.cubby.host
    build:
      context: .
      dockerfile: source/Scribbly.Cubby.Host/Dockerfile

